<a href="https://colab.research.google.com/github/adeleke1508/flyrank_week_one_ml_project_1/blob/main/work/notebooks/w04_baseline_score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/adeleke1508/flyrank_week_one_ml_project_1/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('/content/drive/MyDrive/dim_content_and_fact_daily_performance_month_2026_05_cleaned.csv')
df.head(n=10)

,client_hash_id_x,content_hash_id,keyword_hash_id,url_hash_id,keyword_char_count,keyword_token_count,url_char_count,content_created_date,content_updated_date,content_type,...,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,ctr,engagement_rate,scroll_rate,ai_traffics_pct
0,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
1,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000164,0.0,0.0,0.0
2,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
3,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
4,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
5,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
6,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
7,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
8,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
9,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0

In [5]:
df.columns

Index(['client_hash_id_x', 'content_hash_id', 'keyword_hash_id', 'url_hash_id',
       'keyword_char_count', 'keyword_token_count', 'url_char_count',
       'content_created_date', 'content_updated_date', 'content_type',
       'search_volume', 'competition', 'competition_level', 'cpc',
       'main_intent', 'backlinks', 'category_count', 'keyword_created_date',
       'provider_used', 'model_used', 'char_count', 'word_count',
       'last_optimized_date', 'optimization_eligible_date', 'is_published',
       'is_deleted', 'report_date', 'client_hash_id_y', 'client_has_gsc',
       'client_has_ga4', 'gsc_data_available', 'ga4_data_available',
       'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position',
       'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions',
       'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct',
       'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai',
       'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude',
       'ai_meta', 'ai_other', 'scroll_events', 'ctr', 'engagement_rate',
       'scroll_rate', 'ai_traffics_pct'],
      dtype='object')

In [6]:
date_cols = [col for col in df.columns if 'date' in col.lower()]
df[date_cols] = df[date_cols].apply(pd.to_datetime,errors='coerce')

In [7]:
df.head(n=10)

,client_hash_id_x,content_hash_id,keyword_hash_id,url_hash_id,keyword_char_count,keyword_token_count,url_char_count,content_created_date,content_updated_date,content_type,...,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,ctr,engagement_rate,scroll_rate,ai_traffics_pct
0,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
1,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000164,0.0,0.0,0.0
2,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
3,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
4,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
5,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
6,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
7,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
8,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
9,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0

In [8]:
earliest_date_of_creation = df['content_created_date'].min()
latest_date_of_creation = df['content_created_date'].max()

earliest_date_of_update = df['content_updated_date'].min()
latest_date_of_upate = df['content_updated_date'].max()

In [9]:
earliest_date_of_creation, latest_date_of_creation

(Timestamp('2026-01-20 00:00:00'), Timestamp('2026-05-31 00:00:00'))

In [10]:
earliest_date_of_update, latest_date_of_upate

(Timestamp('2026-05-20 00:00:00'), Timestamp('2026-07-06 00:00:00'))

In [11]:
print(df['content_created_date'].dtype)

datetime64[ns]

In [12]:
df['old'] = np.where(df['content_created_date'] <= '2026-03-15' , 1, 0)

In [13]:
df.head()

,client_hash_id_x,content_hash_id,keyword_hash_id,url_hash_id,keyword_char_count,keyword_token_count,url_char_count,content_created_date,content_updated_date,content_type,...,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,ctr,engagement_rate,scroll_rate,ai_traffics_pct,old
0,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0
1,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.000164,0.0,0.0,0.0,0
2,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0
3,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0
4,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0

In [14]:
conditions = (df['old']==1) & (df['content_updated_date'] <='2026-06-13')
df['old_but_updated_recently'] = np.where(conditions, 1, 0)

In [15]:
df.head()

,client_hash_id_x,content_hash_id,keyword_hash_id,url_hash_id,keyword_char_count,keyword_token_count,url_char_count,content_created_date,content_updated_date,content_type,...,ai_claude,ai_meta,ai_other,scroll_events,ctr,engagement_rate,scroll_rate,ai_traffics_pct,old,old_but_updated_recently
0,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0
1,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.000164,0.0,0.0,0.0,0,0
2,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0
3,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0
4,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0

In [16]:
df['ctr'].max()

0.01

In [17]:
df['ctr'].mean()

np.float64(4.522385200609292e-05)

In [18]:
df.head()

,client_hash_id_x,content_hash_id,keyword_hash_id,url_hash_id,keyword_char_count,keyword_token_count,url_char_count,content_created_date,content_updated_date,content_type,...,ai_claude,ai_meta,ai_other,scroll_events,ctr,engagement_rate,scroll_rate,ai_traffics_pct,old,old_but_updated_recently
0,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0
1,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.000164,0.0,0.0,0.0,0,0
2,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0
3,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0
4,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0

In [19]:
df['ctr'].describe()

count    293868.000000
mean          0.000045
std           0.000207
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000014
max           0.010000
Name: ctr, dtype: float64

In [20]:
(df['ctr'] ==0.01).mean()

np.float64(0.00014632419998094384)

In [22]:
df['gsc_impressions'].describe()

count    293868.000000
mean        136.709131
std         326.581282
min           1.000000
25%          14.000000
50%          46.000000
75%         131.000000
max       21364.000000
Name: gsc_impressions, dtype: float64

In [23]:
df['ctr_fixed'] = df['gsc_clicks']/df['gsc_impressions']

In [24]:
df['ctr_fixed'] = df['ctr_fixed'].replace([np.inf, -np.inf],(np.nan)).fillna(0)

In [25]:
df.head(n=10)

,client_hash_id_x,content_hash_id,keyword_hash_id,url_hash_id,keyword_char_count,keyword_token_count,url_char_count,content_created_date,content_updated_date,content_type,...,ai_meta,ai_other,scroll_events,ctr,engagement_rate,scroll_rate,ai_traffics_pct,old,old_but_updated_recently,ctr_fixed
0,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0,0.000000
1,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.000164,0.0,0.0,0.0,0,0,0.016393
2,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0,0.000000
3,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0,0.000000
4,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0,0.000000
5,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0,0.000000
6,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0,0.000000
7,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0,0.000000
8,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0,0.000000
9,client_06d356715a8ff3b6,content_0059a4d4195810c9,keyword_334c23e29ae07e53,url_dcae6d712ab26f8e,36,7,100,2026-04-16,2026-06-23,keyword article,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0,0.000000

In [26]:
df['ctr_fixed'].describe()

count    293868.000000
mean          0.004522
std           0.020697
min           0.000000
25%           0.000000
50%           0.000000
75%           0.001359
max           1.000000
Name: ctr_fixed, dtype: float64

## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*

Rule 1: 'Old content that hasn't been refreshed gets a lower ctr than other content'

Rule 2: “The better a page’s average search position, the higher its CTR.”

In [28]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
#Reason Code for Rule Number One.

r = df[df['gsc_impressions'] >= 100].copy()

def stale_group(d):
  if d['old'] == 0:
    return '1_fresh'
  return  '2_old_recent_update' if d['old_but_updated_recently'] == 1 else '3_old_not_updated'

r['stale_group'] = r.apply(stale_group, axis=1)

bucket_table_A = r.groupby('stale_group').agg(
    n=('ctr_fixed', 'size'),
    mean_ctr = ('ctr_fixed', 'mean'),
    median_ctr = ('ctr_fixed', 'median'),
    pct_zero_clicks = ('gsc_clicks', lambda s: ( s == 0 ).mean()),
)

bucket_table_A

                         n  mean_ctr  median_ctr  pct_zero_clicks
stale_group
1_fresh              22513  0.004802    0.002778         0.434771
2_old_recent_update  16914  0.003826    0.001361         0.479011
3_old_not_updated    52373  0.004402    0.002154         0.442346

Verdict:Mixed
1.Fresh pages have the highest CTR, but old-not-updated pages are only slightly behind (mean 0.0044 vs 0.0048; zero-click share 44% vs 43%), and old pages that were recently updated do worst (0.0038, 48% zero-click). Staleness alone separates CTR weakly and inconsistently, so verdict: MIXED.

In [30]:
#Reason code for rule 2
r['pos_bucket'] = pd.cut(r['gsc_avg_position'], [0, 3, 10, 20 , 50, 100, np.inf])
bucket_table_b = r.groupby('pos_bucket', observed=True).agg(
    n=('ctr_fixed', 'size'),
    mean_ctr = ('ctr_fixed', 'mean'),
    median_ctr = ('ctr_fixed', 'median'),
    pct_zero_clicks = ('gsc_clicks', lambda s: ( s == 0 ).mean()),
)

bucket_table_b

                   n  mean_ctr  median_ctr  pct_zero_clicks
pos_bucket
(0.0, 3.0]      2147  0.007310    0.006173         0.227294
(3.0, 10.0]    67064  0.004502    0.002591         0.414664
(10.0, 20.0]   15316  0.004141    0.000000         0.540415
(20.0, 50.0]    6933  0.003183    0.000000         0.605510
(50.0, 100.0]    339  0.000688    0.000000         0.837758

Verdict:Confirmed
CTR falls monotonically as average position worsens: mean CTR drops from 0.0073 (positions 1-3) to 0.0007 (positions 51-100), and the zero-click share rises from 23% to 84%. Position clearly drives CTR, so comparing a page’s CTR to the norm for its position bucket is justified. Verdict: CONFIRMED. Caveat: the 51-100 bucket has only 339 rows, so its average is less reliable.

## 2. Build the ranked queue (writes the CSV)

*Code the score, rank everything, write work/outputs/baseline_action_score.csv.*

In [38]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
d = df[df['gsc_impressions'] >= 100].copy()
d = d.sort_values('report_date')
d['pos_x_imp'] = d['gsc_avg_position'] * d['gsc_impressions']

pages = d.groupby('content_hash_id').agg(
    client=('client_hash_id_x', 'first'),
    content_type=('content_type', 'first'),
    old=('old', 'last'),
    old_but_updated_recently=('old_but_updated_recently', 'last'),
    impressions=('gsc_impressions', 'sum'),
    clicks=('gsc_clicks', 'sum'),
    pos_x_imp=('pos_x_imp', 'sum'),
    n_reports=('report_date', 'nunique'),
).reset_index()

pages['avg_position'] = pages['pos_x_imp'] / pages['impressions']
pages['ctr'] = pages['clicks'] / pages['impressions']
pages = pages[pages['impressions'] >= 100].copy()

pages['pos_bucket'] = pd.cut(pages['avg_position'], [0, 3, 5, 7, 10, 20, 50, 100])
g = pages.groupby('pos_bucket', observed=True)
pages['expected_ctr'] = g['clicks'].transform('sum') / g['impressions'].transform('sum')
pages['ctr_gap'] = (pages['expected_ctr'] - pages['ctr']).clip(lower=0)

flag = (pages['old'] == 1) & (pages['old_but_updated_recently'] == 0) & (pages['ctr_gap'] > 0)
pages['score'] = np.where(flag, pages['impressions'] * pages['ctr_gap'], 0)
pages['reason_code'] = np.where(flag, 'STALE_BELOW_POSITION_CTR', '')
pages['action'] = np.where(flag, 'REFRESH', 'NONE')

queue = pages[flag].sort_values('score', ascending=False)

In [39]:
queue.to_csv('baseline_action_score.csv', index=False)

In [40]:
queue.head(20)

,content_hash_id,client,content_type,old,old_but_updated_recently,impressions,clicks,pos_x_imp,n_reports,avg_position,ctr,pos_bucket,expected_ctr,ctr_gap,score,reason_code,action
4775,content_e578ac84778da489,client_73cda7b4e4f265ea,keyword article,1,0,135829,124,889749.0,31,6.550508,0.000913,"(5, 7]",0.004099,0.003186,432.794386,STALE_BELOW_POSITION_CTR,REFRESH
3731,content_b236ccce55b3ef86,client_73cda7b4e4f265ea,keyword article,1,0,86721,161,431775.0,31,4.978898,0.001857,"(3, 5]",0.005714,0.003858,334.530818,STALE_BELOW_POSITION_CTR,REFRESH
3189,content_987d251ee617d9c6,client_73cda7b4e4f265ea,keyword article,1,0,154212,551,649979.0,31,4.214841,0.003573,"(3, 5]",0.005714,0.002141,330.179858,STALE_BELOW_POSITION_CTR,REFRESH
5197,content_fa19b056cd7a49a4,client_73cda7b4e4f265ea,keyword article,1,0,138754,503,439954.0,31,3.170748,0.003625,"(3, 5]",0.005714,0.002089,289.851594,STALE_BELOW_POSITION_CTR,REFRESH
3184,content_97ff27515379c0ca,client_73cda7b4e4f265ea,keyword article,1,0,100892,316,495675.0,31,4.912927,0.003132,"(3, 5]",0.005714,0.002582,260.505060,STALE_BELOW_POSITION_CTR,REFRESH
2356,content_6eda21f7025fe783,client_23a62021009f63c4,keyword article,1,0,98383,150,509498.0,31,5.178720,0.001525,"(5, 7]",0.004099,0.002575,253.294599,STALE_BELOW_POSITION_CTR,REFRESH
82,content_036a7b994ba532fa,client_73cda7b4e4f265ea,keyword article,1,0,105566,203,726903.0,31,6.885768,0.001923,"(5, 7]",0.004099,0.002176,229.739372,STALE_BELOW_POSITION_CTR,REFRESH
1845,content_57768353f230d65d,client_73cda7b4e4f265ea,keyword article,1,0,94445,320,440476.0,31,4.663836,0.003388,"(3, 5]",0.005714,0.002326,219.666380,STALE_BELOW_POSITION_CTR,REFRESH
1297,content_3d228684be08111a,client_73cda7b4e4f265ea,keyword article,1,0,72772,82,495027.0,31,6.802438,0.001127,"(5, 7]",0.004099,0.002972,216.309205,STALE_BELOW_POSITION_CTR,REFRESH
2861,content_881043852b83a83a,client_73cda7b4e4f265ea,keyword article,1,0,67186,181,328285.0,31,4.886211,0.002694,"(3, 5]",0.005714,0.003020,202.906246,STALE_BELOW_POSITION_CTR,REFRESH
3446,content_a503431efe530d6a,client_73cda7b4e4f265ea,keyword article,1,0,100850,214,506340.0,31,5.020724,0.002122,"(5, 7]",0.004099,0.001977,199.407401,STALE_BELOW_POSITION_CTR,REFRESH
3044,content_91188c63e6dc39c7,client_e5c2aa26a8598242,keyword article,1,0,37847,22,179070.0,31,4.731419,0.000581,"(3, 5]",0.005714,0.005133,194.260823,STALE_BELOW_POSITION_CTR,REFRESH
4850,content_e905a3e68f395962,client_73cda7b4e4f265ea,keyword article,1,0,68079,258,189304.0,31,2.780652,0.003790,"(0, 3]",0.006585,0.002795,190.270742,STALE_BELOW_POSITION_CTR,REFRESH
1738,content_529653684b77a50e,client_73cda7b4e4f265ea,keyword article,1,0,47558,83,164774.0,31,3.464696,0.001745,"(3, 5]",0.005714,0.003969,188.750264,STALE_BELOW_POSITION_CTR,REFRESH
1243,content_3aaa0ab12cdb43a4,client_73cda7b4e4f265ea,keyword article,1,0,94809,102,679600.0,31,7.168096,0.001076,"(7, 10]",0.002876,0.001800,170.670426,STALE_BELOW_POSITION_CTR,REFRESH
2812,content_85e64f602b0f92eb,client_73cda7b4e4f265ea,keyword article,1,0,35316,39,171310.0,31,4.850776,0.001104,"(3, 5]",0.005714,0.004610,162.798484,STALE_BELOW_POSITION_CTR,REFRESH
229,content_0a5ab31a60b43569,client_e5c2aa26a8598242,keyword article,1,0,43530,39,258057.0,31,5.928256,0.000896,"(5, 7]",0.004099,0.003203,139.439506,STALE_BELOW_POSITION_CTR,REFRESH
2907,content_8a5f2d8f83c9b311,client_73cda7b4e4f265ea,keyword article,1,0,36208,78,178738.0,31,4.936423,0.002154,"(3, 5]",0.005714,0.003560,128.895445,STALE_BELOW_POSITION_CTR,REFRESH
4013,content_bea53269ccec2c3b,client_73cda7b4e4f265ea,keyword article,1,0,44160,59,274741.0,31,6.221490,0.001336,"(5, 7]",0.004099,0.002763,122.022021,STALE_BELOW_POSITION_CTR,REFRESH
315,content_0e3f93e573464a71,client_73cda7b4e4f265ea,keyword article,1,0,99004,287,503494.0,31,5.085593,0.002899,"(5, 7]",0.004099,0.001200,118.840221,STALE_BELOW_POSITION_CTR,REFRESH

## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*

1.content_e578 (REFRESH): 135,829 impressions, 124 clicks, CTR 0.09% vs 0.41% typical at position 6.6, so about 433 clicks missed. Wrong if the position average hides a swing (for example a few days at position 2 and most at 12) or a SERP feature is absorbing the clicks.
2.content_b236 (REFRESH): 86,721 impressions, 161 clicks, CTR 0.19% vs 0.57% at position 5.0, so about 335 missed. Wrong if position 5.0 is right at the (3,5]/(5,7] boundary and the page really belongs to the lower-CTR bucket, which would shrink the gap.
3.content_987d (REFRESH): the most impressions in the list (154,212), 551 clicks, CTR 0.36% vs 0.57% at position 4.2, so about 330 missed. Wrong if the gap is only 37% below normal and the page’s keyword is naturally low-CTR (informational queries answered directly on the results page).
4.content_fa19 (REFRESH): 138,754 impressions, 503 clicks, CTR 0.36% vs 0.57% at position 3.17, so about 290 missed. Wrong if the true position is under 3: just past the boundary it would be judged against the 0.66% benchmark, which would make the gap bigger, so the rank is sensitive to the bucket edges.
5.content_97ff (REFRESH): 100,892 impressions, 316 clicks, CTR 0.31% vs 0.57% at position 4.9, so about 261 missed. Wrong if the page’s title and snippet are already strong and the shortfall is simply seasonal demand.
6.content_6eda (REFRESH): the only top-20 page from client_23a6..., 98,383 impressions, 150 clicks, CTR 0.15% vs 0.41% at position 5.2, so about 253 missed. Wrong if this client’s whole site has lower CTR than the pooled benchmark, so the gap is a client effect and not a page problem.
7.content_036a (REFRESH): 105,566 impressions, 203 clicks, CTR 0.19% vs 0.41% at position 6.9, so about 230 missed. Wrong if the position is really near 7 and it is being compared with a bucket that has a higher CTR than pages at the bottom of it.
8.content_5776 (REFRESH): 94,445 impressions, 320 clicks, CTR 0.34% vs 0.57% at position 4.7, so about 220 missed. Wrong if its refresh date is close to the report window and CTR is still recovering from a recent change.
9.content_3d22 (REFRESH): 72,772 impressions, 82 clicks, CTR 0.11% vs 0.41% at position 6.8, so about 216 missed. Wrong if the traffic is driven by queries where users expect an answer in the snippet (low click intent).
10.content_8810 (REFRESH): 67,186 impressions, 181 clicks, CTR 0.27% vs 0.57% at position 4.9, so about 203 missed. Wrong if a competing result ranked just above it takes most of the clicks, so a refresh of this page alone wouldn’t change much.
11.content_a503 (REFRESH): 100,850 impressions, 214 clicks, CTR 0.21% vs 0.41% at position 5.02, so about 199 missed. Wrong if the position sits on the (3,5]/(5,7] boundary and the correct benchmark is the higher one, which would put it higher up.
12.content_9118 (REFRESH): client_e5c2..., 37,847 impressions, only 22 clicks, CTR 0.06% vs 0.57% at position 4.7, so about 194 missed. This is a gap of nearly 10x, much bigger than most rows. Wrong if tracking is broken for this URL, for example a redirect or a canonical pointing elsewhere, since clicks that are this low suggest a technical problem, not stale content.
13.content_e905 (REFRESH): 68,079 impressions, 258 clicks, CTR 0.38% vs 0.66% at position 2.8, so about 190 missed. Wrong if it is mostly branded or navigational traffic at the top of the results, where clicks go elsewhere.
14.content_5296 (REFRESH): 47,558 impressions, 83 clicks, CTR 0.17% vs 0.57% at position 3.5, so about 189 missed. Wrong if its position moved a lot over the 31 days, so the average (3.5) misrepresents where it actually sat.
15.content_3aaa (REFRESH): 94,809 impressions, 102 clicks, CTR 0.11% vs 0.29% at position 7.2, so about 171 missed. Wrong if the (7,10] benchmark is too low because that bucket is dominated by other weak pages, which would understate how bad it is, or too high for pages at the very bottom of the range.
16.content_85e6 (REFRESH): 35,316 impressions, 39 clicks, CTR 0.11% vs 0.57% at position 4.9, so about 163 missed. Wrong if the page has a much smaller audience than the others and normal day-to-day variation explains the shortfall.
17.content_0a5a (REFRESH): client_e5c2..., 43,530 impressions, 39 clicks, CTR 0.09% vs 0.41% at position 5.9, so about 139 missed. Wrong if the same client-level problem as row 12 is behind it, since both rows come from that client.
18.content_8a5f (REFRESH): 36,208 impressions, 78 clicks, CTR 0.22% vs 0.57% at position 4.9, so about 129 missed. Wrong if the number of impressions comes from a short burst of days that doesn’t represent the page’s usual traffic.
19.content_bea5 (REFRESH): 44,160 impressions, 59 clicks, CTR 0.13% vs 0.41% at position 6.2, so about 122 missed. Wrong if its CTR was fine before some other change (a competitor, a SERP layout shift), so the cause isn’t staleness.
20.content_0e3f (REFRESH): 99,004 impressions, 287 clicks, CTR 0.29% vs 0.41% at position 5.1, so about 119 missed. The weakest of the 20 (about 29% below normal). Wrong if the gap is within normal page-to-page variation, in which case nothing is actually wrong with this page.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. Weak picks + leakage check

*Which picks look wrong and why? Confirm no product flags or future windows leaked in.*

Weakest picks:

Rank 20 (content_0e3f): CTR is only about 29% below the benchmark for its position. It is in the top 20 because of volume (99k impressions), and that gap is within normal page-to-page variation. This is the pick I trust least.
Ranks 12 and 17 (client_e5c2...): the gaps are very large (rank 12 has about 10× fewer clicks than expected). A gap that size looks more like a tracking or technical problem (redirect, canonical, broken GSC mapping) than stale content, so “REFRESH” may be the wrong action.
Ranks 2 and 4 (content_b236, content_fa19): their average positions (4.98 and 3.17) sit almost on a bucket edge. A small shift moves them to a different benchmark and changes their score, so their rank is sensitive to my bucketing.
Client concentration: 17 of the top 20 are from one client. Either that client has the most impressions, or the pooled benchmark is unfair to it. A per-client benchmark would be the fix.
The staleness filter is weak. Signal A came out MIXED, so “old and not updated” is a weak ingredient. This queue mostly finds high-traffic pages that underperform for their position, and the label “stale” is only partly supported.

In [41]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
print(df[['old','old_but_updated_recently']].describe())
age_days = (pd.to_datetime(df['report_date']) - pd.to_datetime(df['content_updated_date'])).dt.days
print(age_days.groupby(df['old']).describe())

                 old  old_but_updated_recently
count  293868.000000             293868.000000
mean        0.714021                  0.247441
std         0.451880                  0.431526
min         0.000000                  0.000000
25%         0.000000                  0.000000
50%         1.000000                  0.000000
75%         1.000000                  0.000000
max         1.000000                  1.000000
        count       mean        std   min   25%   50%   75%   max
old
0     84040.0 -34.022989  13.481353 -66.0 -44.0 -34.0 -25.0  11.0
1    209828.0 -32.826529  14.974968 -66.0 -43.0 -34.0 -23.0  11.0

In [42]:
print((pd.to_datetime(df['content_updated_date']) > pd.to_datetime(df['report_date'])).sum())

286649

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.